config/routes.rb
Rails.application.routes.draw do

  resources :giraffes, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/giraffe.rb
class Giraffe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/giraffes_controller.rb
class GiraffesController < ApplicationController
  def index
    @giraffes = Giraffe.all
  end

  def new
    @giraffes = Giraffe.new
  end

  def create
    @giraffe = Giraffe.new(safe_params)
    if @giraffe.save
      redirect_to giraffes_url, notice: "Successfully saved giraffe!"
    else
      flash.now[:notice] = "There was a problem saving your giraffe!"
      render :new
    end
  end

  private
    def safe_params
      params.require(:giraffe).permit(:name, :age, :color)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/giraffes_helper.rb
module GiraffesHelper
end

app/views/giraffes/index.html.erb
<h1>Your Giraffes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Age</th>
    </tr>
  </thead>
  <tbody>
    <% @giraffes.each do |giraffe| %>
      <tr>
        <td><%= giraffe.name %></td>
        <td><%= giraffe.color %></td>
        <td><%= giraffe.age %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add a Giraffe', new_giraffe_url %>

app/views/giraffes/new.html.erb
<h1>Create a giraffe</h1>

<%= form_for @giraffes do |giraffe_fields| %>

  <%= giraffe_fields.label :name %>
  <%= giraffe_fields.text_field :name %><br>

  <%= giraffe_fields.label :color %>
  <%= giraffe_fields.text_field :color %><br>

  <%= giraffe_fields.label :age %>
  <%= giraffe_fields.number_field :age %><br>

  <%= giraffe_fields.submit %>

<% end %>

<%= link_to 'List Giraffes', giraffes_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiraffeDaycare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>